// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fir_fixed,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z007s-clg225-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.508000,HLS_SYN_LAT=403,HLS_SYN_TPT=none,HLS_SYN_MEM=1,HLS_SYN_DSP=1,HLS_SYN_FF=130,HLS_SYN_LUT=194,HLS_VERSION=2019_1}" *)

module fir_fixed (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_V,
        h_V_address0,
        h_V_ce0,
        h_V_q0,
        y_V,
        y_V_ap_vld
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_pp0_stage0 = 6'd8;
parameter    ap_ST_fsm_pp0_stage1 = 6'd16;
parameter    ap_ST_fsm_state7 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] x_V;
output  [6:0] h_V_address0;
output   h_V_ce0;
input  [15:0] h_V_q0;
output  [16:0] y_V;
output   y_V_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg h_V_ce0;
reg y_V_ap_vld;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [6:0] regs_V_address0;
reg    regs_V_ce0;
reg    regs_V_we0;
reg   [15:0] regs_V_d0;
wire   [15:0] regs_V_q0;
reg   [16:0] p_Val2_s_reg_143;
reg   [6:0] i1_0_reg_156;
wire  signed [31:0] sext_ln8_fu_174_p1;
reg  signed [31:0] sext_ln8_reg_255;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_1_fu_178_p3;
wire   [0:0] icmp_ln9_fu_186_p2;
reg   [0:0] icmp_ln9_reg_264;
wire   [7:0] grp_fu_167_p2;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln14_fu_201_p2;
reg   [0:0] icmp_ln14_reg_278;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state4_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [6:0] i_1_fu_207_p2;
reg   [6:0] i_1_reg_282;
reg    ap_enable_reg_pp0_iter0;
reg  signed [15:0] h_V_load_reg_297;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state5_pp0_stage1_iter0;
wire    ap_block_pp0_stage1_11001;
reg  signed [15:0] regs_V_load_1_reg_302;
wire   [31:0] lhs_V_fu_219_p3;
reg   [31:0] lhs_V_reg_307;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state4;
wire    ap_block_pp0_stage1_subdone;
wire  signed [7:0] ap_phi_mux_i_0_phi_fu_135_p4;
reg  signed [7:0] i_0_reg_131;
wire    ap_block_pp0_stage0;
reg   [6:0] ap_phi_mux_i1_0_phi_fu_160_p4;
wire   [63:0] zext_ln12_1_fu_192_p1;
wire   [63:0] zext_ln12_fu_197_p1;
wire   [63:0] zext_ln15_fu_213_p1;
wire    ap_CS_fsm_state7;
reg  signed [7:0] grp_fu_167_p0;
wire    ap_block_pp0_stage1;
wire  signed [31:0] grp_fu_242_p3;
reg   [5:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

fir_fixed_regs_V #(
    .DataWidth( 16 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
regs_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(regs_V_address0),
    .ce0(regs_V_ce0),
    .we0(regs_V_we0),
    .d0(regs_V_d0),
    .q0(regs_V_q0)
);

fir_fixed_mac_mulbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fir_fixed_mac_mulbkb_U1(
    .din0(regs_V_load_1_reg_302),
    .din1(h_V_load_reg_297),
    .din2(lhs_V_reg_307),
    .dout(grp_fu_242_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state4) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((tmp_1_fu_178_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone)))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((tmp_1_fu_178_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_fu_178_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i1_0_reg_156 <= 7'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln14_reg_278 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        i1_0_reg_156 <= i_1_reg_282;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_0_reg_131 <= grp_fu_167_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_0_reg_131 <= 8'd99;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_fu_178_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        p_Val2_s_reg_143 <= 17'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln14_reg_278 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        p_Val2_s_reg_143 <= {{grp_fu_242_p3[31:15]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_reg_278 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        h_V_load_reg_297 <= h_V_q0;
        lhs_V_reg_307[31 : 15] <= lhs_V_fu_219_p3[31 : 15];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_1_reg_282 <= i_1_fu_207_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln14_reg_278 <= icmp_ln14_fu_201_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_fu_178_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        icmp_ln9_reg_264 <= icmp_ln9_fu_186_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_reg_278 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        regs_V_load_1_reg_302 <= regs_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        sext_ln8_reg_255 <= sext_ln8_fu_174_p1;
    end
end

always @ (*) begin
    if ((icmp_ln14_fu_201_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state4 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state4 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln14_reg_278 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_i1_0_phi_fu_160_p4 = i_1_reg_282;
    end else begin
        ap_phi_mux_i1_0_phi_fu_160_p4 = i1_0_reg_156;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_167_p0 = i_0_reg_131;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_167_p0 = ap_phi_mux_i_0_phi_fu_135_p4;
    end else begin
        grp_fu_167_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        h_V_ce0 = 1'b1;
    end else begin
        h_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        regs_V_address0 = zext_ln15_fu_213_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        regs_V_address0 = zext_ln12_fu_197_p1;
    end else if (((icmp_ln9_fu_186_p2 == 1'd1) & (tmp_1_fu_178_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        regs_V_address0 = 7'd0;
    end else if (((icmp_ln9_fu_186_p2 == 1'd0) & (tmp_1_fu_178_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        regs_V_address0 = zext_ln12_1_fu_192_p1;
    end else begin
        regs_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln9_fu_186_p2 == 1'd0) & (tmp_1_fu_178_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((icmp_ln9_fu_186_p2 == 1'd1) & (tmp_1_fu_178_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        regs_V_ce0 = 1'b1;
    end else begin
        regs_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        regs_V_d0 = regs_V_q0;
    end else if (((icmp_ln9_fu_186_p2 == 1'd1) & (tmp_1_fu_178_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        regs_V_d0 = x_V;
    end else begin
        regs_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln9_reg_264 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((icmp_ln9_fu_186_p2 == 1'd1) & (tmp_1_fu_178_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        regs_V_we0 = 1'b1;
    end else begin
        regs_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        y_V_ap_vld = 1'b1;
    end else begin
        y_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_1_fu_178_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln14_fu_201_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((icmp_ln14_fu_201_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_mux_i_0_phi_fu_135_p4 = i_0_reg_131;

assign grp_fu_167_p2 = ($signed(grp_fu_167_p0) + $signed(8'd255));

assign h_V_address0 = zext_ln15_fu_213_p1;

assign i_1_fu_207_p2 = (ap_phi_mux_i1_0_phi_fu_160_p4 + 7'd1);

assign icmp_ln14_fu_201_p2 = ((ap_phi_mux_i1_0_phi_fu_160_p4 == 7'd100) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_186_p2 = ((i_0_reg_131 == 8'd0) ? 1'b1 : 1'b0);

assign lhs_V_fu_219_p3 = {{p_Val2_s_reg_143}, {15'd0}};

assign sext_ln8_fu_174_p1 = i_0_reg_131;

assign tmp_1_fu_178_p3 = i_0_reg_131[32'd7];

assign y_V = p_Val2_s_reg_143;

assign zext_ln12_1_fu_192_p1 = grp_fu_167_p2;

assign zext_ln12_fu_197_p1 = $unsigned(sext_ln8_reg_255);

assign zext_ln15_fu_213_p1 = ap_phi_mux_i1_0_phi_fu_160_p4;

always @ (posedge ap_clk) begin
    lhs_V_reg_307[14:0] <= 15'b000000000000000;
end

endmodule //fir_fixed
